services:
  prod_db:
    image: mysql
    restart: always
    environment: 
      MYSQL_ROOT_PASSWORD: ${MYSQL_DEVELOPMENT_PASSWORD}
      MYSQL_DATABASE: ${MYSQL_DEVELOPMENT_DATABASE}
    ports:
      - ${MYSQL_DEVELOPMENT_PORT}:3306
  dev_db:
    image: mysql
    restart: always
    environment: 
      MYSQL_ROOT_PASSWORD: ${MYSQL_PRODUCTION_PASSWORD}
      MYSQL_DATABASE: ${MYSQL_PRODUCTION_DATABASE}
    ports:
      - ${MYSQL_PRODUCTION_PORT}:3306