@host = http://127.0.0.1:8080

###
# @name locationPost
POST {{host}}/locations
Content-Type: application/json
Accept: application/json
oidc_claim_ismemberof: admin

{
    "site": "Sciences", 
    "name": "EPA"
}

###
@locationId = {{locationPost.response.body.$.locationId}}

###
DELETE {{host}}/locations/{{locationId}}
oidc_claim_ismemberof: admin

###
GET {{host}}/locations
Content-Type: application/json
Accept: application/json

###
GET {{host}}/locations?site=Sciences
Content-Type: application/json
Accept: application/json

###
GET {{host}}/locations/{{locationId}}
Content-Type: application/json
Accept: application/json

### unauthorized lockers post
POST {{host}}/lockers
Content-Type: application/json
Accept: application/json

{
    "number": 26, 
    "verticalPosition": "En bas",
    "lock": false,
    "locationId":1
}


###
# @name lockerPost
POST {{host}}/lockers
Content-Type: application/json
Accept: application/json
oidc_claim_ismemberof: admin

{
    "number": 22, 
    "verticalPosition": "En bas",
    "lock": false,
    "locationId":1,
    "dimensions": "100/50/80"
}

###
@lockerId = {{lockerPost.response.body.$.lockerId}}

###
GET {{host}}/lockers
Content-Type: application/json
Accept: application/json

###
GET {{host}}/lockers/{{lockerId}}
Content-Type: application/json
Accept: application/json

###
POST {{host}}/contracts
Content-Type: application/json
Accept: application/json
oidc_claim_given_name: Bilbo
oidc_claim_family_name: Baggins
oidc_claim_email: bilbo@gmail.com

{
    "lockerId": "{{lockerId}}"
}

### admin creates a locker for someone else
POST {{host}}/contracts
Content-Type: application/json
Accept: application/json
oidc_claim_given_name: Bilbo
oidc_claim_family_name: Baggins
oidc_claim_email: bilbo@gmail.com
oidc_claim_ismemberof: admin

{
    "email": "tim@python.co.uk",
    "firstname": "John",
    "lastname": "Cleese",
    "lockerId": "95ac150a-8101-46be-a275-a21318e849b2"
}

###
GET {{host}}/contracts
Content-Type: application/json
Accept: application/json
oidc_claim_email: bilbo@gmail.com

###
GET {{host}}/contracts
Content-Type: application/json
Accept: application/json
oidc_claim_ismemberof: admin

###
GET {{host}}/contracts
Content-Type: application/json
Accept: application/json

###
POST {{host}}/contracts
Content-Type: application/json
Accept: application/json

{
    "lockerId": "{{lockerId}}"
}

###
GET {{host}}/contracts/{{lockerId}}
Content-Type: application/json
Accept: application/json
oidc_claim_ismemberof: admin

### if it's the user making the request's locker, return it.
GET {{host}}/contracts/{{lockerId}}
Content-Type: application/json
Accept: application/json
oidc_claim_email: bilbo@gmail.com   

###
DELETE {{host}}/contracts/{{lockerId}}
Content-Type: application/json
Accept: application/json

###
DELETE {{host}}/lockers/{{lockerId}}
Content-Type: application/json
Accept: application/json

###
GET {{host}}/lockers
Content-Type: application/json
Accept: application/json
