@host = http://127.0.0.1:8080

###
# @name locationPost
POST {{host}}/locations
Content-Type: application/json
Accept: application/json

{
    "site": "Sciences", 
    "name": "EPA"
}

###
@locationId = {{locationPost.response.body.$.locationId}}

###
GET {{host}}/locations
Content-Type: application/json
Accept: application/json

###
GET {{host}}/locations?site=Sciences
Content-Type: application/json
Accept: application/json


###
GET {{host}}/locations/{{locationId}}
Content-Type: application/json
Accept: application/json

###
# @name lockerPost
POST {{host}}/lockers
Content-Type: application/json
Accept: application/json

{
    "number": 16, 
    "verticalPosition": "En bas",
    "lock": false,
    "locationId": 5
}

###
@lockerId = {{lockerPost.response.body.$.lockerId}}

###
GET {{host}}/lockers?site=Sciences
Content-Type: application/json
Accept: application/json

###
GET {{host}}/lockers/{{lockerId}}
Content-Type: application/json
Accept: application/json

###
POST {{host}}/contracts
Content-Type: application/json
Accept: application/json

{
    "lockerId": "{{lockerId}}"
}

###
GET {{host}}/contracts
Content-Type: application/json
Accept: application/json

###
GET {{host}}/contracts/337f6867-7fd1-44bb-8dfe-74eb71baf731
Content-Type: application/json
Accept: application/json

