@host = http://127.0.0.1:8080

POST {{host}}/lockers
Content-Type: application/json
Accept: application/json

{
    "number": 14, 
    "verticalPosition": "En bas",
    "lock": false,
    "locationId": 1
}

